apiVersion: v1
kind: Pod
metadata:
  name: utrains
  #namespace: dev
  labels:
   app: utrains
spec:
  containers:
    - name: utrains-app
      image: httpd
      ports:
        - containerPort: 80
          name: http
          protocol: TCP
